language: python
python:
  - 3.6.9
before_install:
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-travis.txt
script: pytest --cov=.
after_success:
  - coveralls